volumes:
  orthanc-storage:
    driver: local
    driver_opts:
      type: none
      device: ./OrthancStorage_sample
      o: bind

services:

  app:
    build:
      context: ./slim
      dockerfile: Dockerfile
      target: app
    ports:
      - "8008:8008"
      - "8080:8080"
    user: nginx
    volumes:
    - ./slim/nginx.conf:/etc/nginx/conf.d/local.conf:ro
    depends_on:
      - orthanc

  orthanc:
    image: jodogne/orthanc-plugins:latest
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=orthanc-wsi
      
secrets:
  orthanc.json:
    file: ./orthanc/orthanc.json