volumes:
  orthanc-storage:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/orthanc/db-v6 # D:/orthanc-storage
      o: bind
  db_data: {}
  arc_data: {}
  ldap_data: {}
  ldap_config: {}

services:

  app:
    build:
      context: ./slim
      dockerfile: Dockerfile
      target: app
    ports:
      - "8008:8008"
      - "8080:8080"
    # extra_hosts:
    #   - "orhtanc:host-gateway"
    user: nginx
    volumes:
    - ./slim/nginx.conf:/etc/nginx/conf.d/local.conf:ro
    depends_on:
      - orthanc

  orthanc:
    image: jodogne/orthanc-plugins
    # build:
    #   context: ./orthanc
    #   dockerfile: Dockerfile
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      # - /usr/lib/x86_64-linux-gnu/libopenslide.so.0.4.1:/libopenslide.so
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=orthanc-wsi
      
secrets:
  orthanc.json:
    file: ./orthanc/orthanc.json